repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: 'https://github.com/psf/black'
    rev: 23.9.1
    hooks:
      - id: black
  - repo: 'https://github.com/pycqa/flake8'
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          - '--ignore=E501'
  - repo: 'https://github.com/pre-commit/pygrep-hooks'
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-use-type-annotations
  - repo: 'https://github.com/tfsec/tfsec'
    rev: v0.58.0
    hooks:
      - id: tfsec
  - repo: 'https://github.com/Yelp/detect-secrets'
    rev: v1.1.0
    hooks:
      - id: detect-secrets
